<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <IsPackable>false</IsPackable>
        <IsTestProject>true</IsTestProject>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Aspire.Hosting.Testing" />
        <PackageReference Include="coverlet.collector">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.NET.Test.Sdk" />
        <PackageReference Include="Reqnroll.xUnit" />
        <PackageReference Include="Shouldly" />
        <PackageReference Include="xunit" />
        <PackageReference Include="xunit.runner.visualstudio" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\MadWorldNL.Umiko.Aspire.Tests\Aspire.Tests.csproj" />
      <ProjectReference Include="..\MadWorldNL.Umiko.Controllers.Api.Contracts\Api.Contracts.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Reference Include="JetBrains.ReSharper.TestRunner.Merged">
        <HintPath>..\..\..\..\..\..\..\Applications\Rider.app\Contents\lib\ReSharperHost\TestRunner\netcoreapp3.0\JetBrains.ReSharper.TestRunner.Merged.dll</HintPath>
      </Reference>
    </ItemGroup>

</Project>
