apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: umiko-ingress
  namespace: {{ .Values.namespace }}
  annotations:
    kubernetes.io/ingress.class: "traefik"
    {{- if .Values.clusterIssuer.enabled }}
    cert-manager.io/cluster-issuer: {{ .Values.clusterIssuer.name | quote }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  tls:
    - secretName: {{ .Values.ingress.tlsSecret }}
      hosts:
        - {{ .Values.ingress.domain }}
        - www.{{ .Values.ingress.domain }}
        - api.{{ .Values.ingress.domain }}
        - bus.{{ .Values.ingress.domain }}
        - admin.{{ .Values.ingress.domain }}
        - database.{{ .Values.ingress.domain }}
  rules:
    - host: api.{{ .Values.ingress.domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.api.name }}
                port:
                  number: {{ .Values.api.servicePort }}
    - host: bus.{{ .Values.ingress.domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.bus.name }}
                port:
                  number: {{ .Values.bus.servicePort }}
    - host: database.{{ .Values.ingress.domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.pgadmin.name }}
                port:
                  number: {{ .Values.pgadmin.servicePort }}
    - host: admin.{{ .Values.ingress.domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.webAdministrators.name }}
                port:
                  number: {{ .Values.webAdministrators.servicePort }}
    - host: www.{{ .Values.ingress.domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.webUsers.name }}
                port:
                  number: {{ .Values.webUsers.servicePort }}
    - host: {{ .Values.ingress.domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.webUsers.name }}
                port:
                  number: {{ .Values.webUsers.servicePort }}