<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\MadWorldNL.Umiko.Application.Domain\Domain.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Aspire.RabbitMQ.Client" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
  </ItemGroup>
</Project>
