<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="coverlet.collector" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" />
        <PackageReference Include="TngTech.ArchUnitNET.xUnit" />
        <PackageReference Include="xunit" />
        <PackageReference Include="xunit.runner.visualstudio" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\MadWorldNL.Umiko.Application.Domain\Domain.csproj" />
        <ProjectReference Include="..\MadWorldNL.Umiko.Application.Functions\Functions.csproj" />
        <ProjectReference Include="..\MadWorldNL.Umiko.Infrastructures.Postgresql\Postgresql.csproj" />
        <ProjectReference Include="..\MadWorldNL.Umiko.Controllers.Api\Api.csproj" />
        <ProjectReference Include="..\MadWorldNL.Umiko.Controllers.Api.Contracts\Api.Contracts.csproj" />
        <ProjectReference Include="..\MadWorldNL.Umiko.Controllers.Bus\Bus.csproj" />
        <ProjectReference Include="..\MadWorldNL.Umiko.Controllers.Web.Administrators\Web.Administrators.csproj" />
        <ProjectReference Include="..\MadWorldNL.Umiko.Controllers.Web.Users\Web.Users.csproj" />
        <ProjectReference Include="..\MadWorldNL.Umiko.Infrastructures.RabbitMQ\RabbitMQ.csproj" />
    </ItemGroup>

    <ItemGroup>
        <Using Include="Xunit"/>
    </ItemGroup>

</Project>