// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace MadWorldNL.Umiko.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class InfrastructureDependencyRulesFeature : object, global::Xunit.IClassFixture<InfrastructureDependencyRulesFeature.FixtureData>, global::Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features", "Infrastructure Dependency Rules", null, global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
        private global::Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "InfrastructureDependencies.feature"
#line hidden
        
        public InfrastructureDependencyRulesFeature(InfrastructureDependencyRulesFeature.FixtureData fixtureData, global::Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        private static global::Io.Cucumber.Messages.Types.Source SourceFunc()
        {
            return new global::Io.Cucumber.Messages.Types.Source("Features/InfrastructureDependencies.feature", @"Feature: Infrastructure Dependency Rules

Scenario: Postgresql should not depend on Functions or Controllers
    Given the architecture is loaded
    Then the Postgresql layer should not depend on the Functions layer
    And the Postgresql layer should not depend on the Api layer
    And the Postgresql layer should not depend on the Api Contracts layer
    And the Postgresql layer should not depend on the Bus layer
    And the Postgresql layer should not depend on the Web Administrators layer
    And the Postgresql layer should not depend on the Web Users layer

Scenario: RabbitMQ should not depend on Functions or Controllers
    Given the architecture is loaded
    Then the RabbitMQ layer should not depend on the Functions layer
    And the RabbitMQ layer should not depend on the Api layer
    And the RabbitMQ layer should not depend on the Api Contracts layer
    And the RabbitMQ layer should not depend on the Bus layer
    And the RabbitMQ layer should not depend on the Web Administrators layer
    And the RabbitMQ layer should not depend on the Web Users layer
", global::Io.Cucumber.Messages.Types.SourceMediaType.TEXT_X_CUCUMBER_GHERKIN_PLAIN);
        }
        
        private static global::Io.Cucumber.Messages.Types.GherkinDocument GherkinDocumentFunc()
        {
            return new global::Io.Cucumber.Messages.Types.GherkinDocument("Features/InfrastructureDependencies.feature", new global::Io.Cucumber.Messages.Types.Feature(new global::Io.Cucumber.Messages.Types.Location(1, new System.Nullable<long>(1)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[0]), "en-US", "Feature", "Infrastructure Dependency Rules", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.FeatureChild>(new global::Io.Cucumber.Messages.Types.FeatureChild[] {
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(3, new System.Nullable<long>(1)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[0]), "Scenario", "Postgresql should not depend on Functions or Controllers", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(4, new System.Nullable<long>(5)), "Given ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONTEXT, "the architecture is loaded", null, null, "c7489e6854a90f5bb212f6b163497f9e"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(5, new System.Nullable<long>(5)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "the Postgresql layer should not depend on the Functions layer", null, null, "39340a22682297589ec814daa0359818"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(6, new System.Nullable<long>(5)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "the Postgresql layer should not depend on the Api layer", null, null, "8ed798c5457ea3579a1bc214d5dd289a"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(7, new System.Nullable<long>(5)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "the Postgresql layer should not depend on the Api Contracts layer", null, null, "9e5f8b353208fa5887ce65f179753857"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(8, new System.Nullable<long>(5)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "the Postgresql layer should not depend on the Bus layer", null, null, "ed03680f7115f9519bd5bb29af2ce0f9"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(9, new System.Nullable<long>(5)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "the Postgresql layer should not depend on the Web Administrators layer", null, null, "69e127b308fae2559f55dd6da06562b5"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(10, new System.Nullable<long>(5)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "the Postgresql layer should not depend on the Web Users layer", null, null, "0a3a573a29ea505f9e0e9530d8054920")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[0]), "3af9e35fb3d977528021429665d7444f")),
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(12, new System.Nullable<long>(1)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[0]), "Scenario", "RabbitMQ should not depend on Functions or Controllers", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(13, new System.Nullable<long>(5)), "Given ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONTEXT, "the architecture is loaded", null, null, "4d0cca38a0aa14558472845f857889d7"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(14, new System.Nullable<long>(5)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "the RabbitMQ layer should not depend on the Functions layer", null, null, "b36864c9749cea568c881af69f256bca"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(15, new System.Nullable<long>(5)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "the RabbitMQ layer should not depend on the Api layer", null, null, "47dea2f3607ddf55ac216ba6efb30ae9"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(16, new System.Nullable<long>(5)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "the RabbitMQ layer should not depend on the Api Contracts layer", null, null, "2425b49a93431e52990b95cfdaff13f2"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(17, new System.Nullable<long>(5)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "the RabbitMQ layer should not depend on the Bus layer", null, null, "78c2db796610565fa0dfbab7d0e75df3"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(18, new System.Nullable<long>(5)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "the RabbitMQ layer should not depend on the Web Administrators layer", null, null, "dbdeb0ec62f36452a22873dd174ccd51"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(19, new System.Nullable<long>(5)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "the RabbitMQ layer should not depend on the Web Users layer", null, null, "0e439b7105f42a52af679147449242d4")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[0]), "0667695924de4a5b939f2e862dd8d48b"))})), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Comment>(new global::Io.Cucumber.Messages.Types.Comment[0]));
        }
        
        private static global::System.Collections.Generic.IEnumerable<Io.Cucumber.Messages.Types.Pickle> PicklesFunc()
        {
            return new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Pickle>(new global::Io.Cucumber.Messages.Types.Pickle[] {
                        new global::Io.Cucumber.Messages.Types.Pickle("58b363633aeb025289ec018638ef2f40", "Features/InfrastructureDependencies.feature", "Postgresql should not depend on Functions or Controllers", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "c7489e6854a90f5bb212f6b163497f9e"}), "b14de749a1e9d95089c7df9e5c1db19f", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "the architecture is loaded"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "39340a22682297589ec814daa0359818"}), "3b2841a8b31b6c57affa614a251cc1ef", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "the Postgresql layer should not depend on the Functions layer"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "8ed798c5457ea3579a1bc214d5dd289a"}), "b7e4e7d57fd31b599e8a8f33c882176a", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "the Postgresql layer should not depend on the Api layer"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "9e5f8b353208fa5887ce65f179753857"}), "db379ff7f0bd795ebbca346bef62ac53", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "the Postgresql layer should not depend on the Api Contracts layer"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "ed03680f7115f9519bd5bb29af2ce0f9"}), "c41da65108d25451bf9aa49af94f7616", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "the Postgresql layer should not depend on the Bus layer"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "69e127b308fae2559f55dd6da06562b5"}), "5fbd22b0ccb97856841116e274e2324a", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "the Postgresql layer should not depend on the Web Administrators layer"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "0a3a573a29ea505f9e0e9530d8054920"}), "cc880cb92b645c57ba7fb5d45247aecb", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "the Postgresql layer should not depend on the Web Users layer")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[0]), new System.Collections.Generic.List<string>(new string[] {
                                        "3af9e35fb3d977528021429665d7444f"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("e37451e35b460b589e54c3dea3876e3e", "Features/InfrastructureDependencies.feature", "RabbitMQ should not depend on Functions or Controllers", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "4d0cca38a0aa14558472845f857889d7"}), "73cd1e4e0f6e7353bcfe5f0d2f58dd6e", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "the architecture is loaded"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "b36864c9749cea568c881af69f256bca"}), "f44c09d78b1ef455b12b7544d4d72c52", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "the RabbitMQ layer should not depend on the Functions layer"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "47dea2f3607ddf55ac216ba6efb30ae9"}), "da02516b2b3a275ba3d657767e698ada", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "the RabbitMQ layer should not depend on the Api layer"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "2425b49a93431e52990b95cfdaff13f2"}), "c788d778a88af156833fde1274615145", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "the RabbitMQ layer should not depend on the Api Contracts layer"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "78c2db796610565fa0dfbab7d0e75df3"}), "d61b049fd93f3f54930df55e93235e06", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "the RabbitMQ layer should not depend on the Bus layer"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "dbdeb0ec62f36452a22873dd174ccd51"}), "37ee984ed816d05bb485baa9e5abc281", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "the RabbitMQ layer should not depend on the Web Administrators layer"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "0e439b7105f42a52af679147449242d4"}), "bdf40b458c278a59b46300d7ef8fd398", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "the RabbitMQ layer should not depend on the Web Users layer")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[0]), new System.Collections.Generic.List<string>(new string[] {
                                        "0667695924de4a5b939f2e862dd8d48b"}))});
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages(new global::System.Func<Io.Cucumber.Messages.Types.Source>(InfrastructureDependencyRulesFeature.SourceFunc), new global::System.Func<Io.Cucumber.Messages.Types.GherkinDocument>(InfrastructureDependencyRulesFeature.GherkinDocumentFunc), new global::System.Func<System.Collections.Generic.IEnumerable<Io.Cucumber.Messages.Types.Pickle>>(InfrastructureDependencyRulesFeature.PicklesFunc));
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
        {
            try
            {
                await this.TestInitializeAsync();
            }
            catch (System.Exception e1)
            {
                try
                {
                    ((global::Xunit.IAsyncLifetime)(this)).DisposeAsync();
                }
                catch (System.Exception e2)
                {
                    throw new System.AggregateException("Test initialization failed", e1, e2);
                }
                throw;
            }
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Postgresql should not depend on Functions or Controllers")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Infrastructure Dependency Rules")]
        [global::Xunit.TraitAttribute("Description", "Postgresql should not depend on Functions or Controllers")]
        public async global::System.Threading.Tasks.Task PostgresqlShouldNotDependOnFunctionsOrControllers()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Postgresql should not depend on Functions or Controllers", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 3
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 4
    await testRunner.GivenAsync("the architecture is loaded", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 5
    await testRunner.ThenAsync("the Postgresql layer should not depend on the Functions layer", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 6
    await testRunner.AndAsync("the Postgresql layer should not depend on the Api layer", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 7
    await testRunner.AndAsync("the Postgresql layer should not depend on the Api Contracts layer", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 8
    await testRunner.AndAsync("the Postgresql layer should not depend on the Bus layer", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 9
    await testRunner.AndAsync("the Postgresql layer should not depend on the Web Administrators layer", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 10
    await testRunner.AndAsync("the Postgresql layer should not depend on the Web Users layer", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="RabbitMQ should not depend on Functions or Controllers")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Infrastructure Dependency Rules")]
        [global::Xunit.TraitAttribute("Description", "RabbitMQ should not depend on Functions or Controllers")]
        public async global::System.Threading.Tasks.Task RabbitMQShouldNotDependOnFunctionsOrControllers()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "1";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("RabbitMQ should not depend on Functions or Controllers", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 12
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 13
    await testRunner.GivenAsync("the architecture is loaded", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 14
    await testRunner.ThenAsync("the RabbitMQ layer should not depend on the Functions layer", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 15
    await testRunner.AndAsync("the RabbitMQ layer should not depend on the Api layer", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 16
    await testRunner.AndAsync("the RabbitMQ layer should not depend on the Api Contracts layer", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 17
    await testRunner.AndAsync("the RabbitMQ layer should not depend on the Bus layer", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 18
    await testRunner.AndAsync("the RabbitMQ layer should not depend on the Web Administrators layer", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 19
    await testRunner.AndAsync("the RabbitMQ layer should not depend on the Web Users layer", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, global::Xunit.IAsyncLifetime
        {
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
            {
                await InfrastructureDependencyRulesFeature.FeatureSetupAsync();
            }
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
            {
                await InfrastructureDependencyRulesFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
