api:
  name: api
  image: ghcr.io/madworldnl/umiko/api
  containerPort: 8080
  servicePort: 80
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 256Mi

bus:
  name: bus
  image: ghcr.io/madworldnl/umiko/bus
  containerPort: 8080
  servicePort: 80
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 256Mi

webUsers:
  name: web-users
  image: ghcr.io/madworldnl/umiko/web-users
  containerPort: 8080
  servicePort: 80
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi

webAdministrators:
  name: web-administrators
  image: ghcr.io/madworldnl/umiko/web-administrators
  containerPort: 8080
  servicePort: 80
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi

postgres:
  name: postgres
  image: postgres
  tag: 17
  containerPort: 5432
  servicePort: 5432
  database: UmikoDb
  username: umiko
  password: changeme
  storageSize: 1Gi
  resources:
    requests:
      cpu: 250m
      memory: 256Mi
    limits:
      cpu: "1"
      memory: 512Mi

rabbitmq:
  name: rabbitmq
  image: rabbitmq
  tag: 4-management
  containerPort: 5672
  managementPort: 15672
  servicePort: 5672
  managementServicePort: 15672
  username: umiko
  password: changeme
  storageSize: 1Gi
  resources:
    requests:
      cpu: 250m
      memory: 256Mi
    limits:
      cpu: "1"
      memory: 512Mi