namespace: umiko-development

appTag: "main"

ingress:
  domain: umiko.dev
  
clusterIssuer:
  enabled: false
  email: "info@umiko.dev"

pgadmin:
  email: admin@umiko.dev
  password: development-password

keycloak:
  adminPassword: development-password
  password: development-password

postgres:
  password: development-password

rabbitmq:
  password: development-password

observability:
  enabled: true
  grafana:
    adminPassword: development-password