namespace: umiko-development

api:
  tag: 0.1.0

bus:
  tag: 0.1.0

webUsers:
  tag: 0.1.0

webAdministrators:
  tag: 0.1.0

postgres:
  password: development-password

rabbitmq:
  password: development-password