namespace: umiko-production

api:
  tag: 0.1.0

bus:
  tag: 0.1.0

webUsers:
  tag: 0.1.0

webAdministrators:
  tag: 0.1.0

ingress:
  domain: umiko.example.com
  certResolver: letsencrypt

postgres:
  password: changeme

rabbitmq:
  password: changeme