namespace: umiko-production

api:
  tag: 0.3.0

bus:
  tag: 0.3.0

webUsers:
  tag: 0.3.0

webAdministrators:
  tag: 0.3.0

ingress:
  domain: umiko.example.com

clusterIssuer:
  enabled: true
  email: "info@umiko.example.com"

pgadmin:
  email: admin@umiko.example.com
  password: changeme

postgres:
  password: changeme

rabbitmq:
  password: changeme