namespace: umiko-development

api:
  tag: 0.1.1

bus:
  tag: 0.1.1

webUsers:
  tag: 0.1.1

webAdministrators:
  tag: 0.1.1

ingress:
  domain: umiko.dev
  
clusterIssuer:
  enabled: false
  email: "info@umiko.dev"

pgadmin:
  email: admin@umiko.dev
  password: development-password

postgres:
  password: development-password

rabbitmq:
  password: development-password