api:
  name: api
  image: ghcr.io/madworldnl/umiko/api
  containerPort: 8080
  servicePort: 80
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 256Mi
      ephemeral-storage: 1Gi

bus:
  name: bus
  image: ghcr.io/madworldnl/umiko/bus
  containerPort: 8080
  servicePort: 80
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 256Mi
      ephemeral-storage: 1Gi

webUsers:
  name: web-users
  image: ghcr.io/madworldnl/umiko/web-users
  containerPort: 8080
  servicePort: 80
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi
      ephemeral-storage: 512Mi

webAdministrators:
  name: web-administrators
  image: ghcr.io/madworldnl/umiko/web-administrators
  containerPort: 8080
  servicePort: 80
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi
      ephemeral-storage: 512Mi

ingress:
  className: traefik
  domain: umiko.local
  tlsSecret: umiko-tls

clusterIssuer:
  enabled: false
  name: "lets-encrypt-umiko"
  email: "info@umiko.local"
  
pgadmin:
  name: pgadmin
  image: dpage/pgadmin4
  tag: "9"
  containerPort: 80
  servicePort: 80
  email: admin@umiko.local
  password: changeme
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
      ephemeral-storage: 1Gi

postgres:
  name: postgres
  image: postgres
  tag: 17
  containerPort: 5432
  servicePort: 5432
  database: UmikoDb
  username: umiko
  password: changeme
  storageSize: 1Gi
  resources:
    requests:
      cpu: 250m
      memory: 256Mi
    limits:
      cpu: "1"
      memory: 512Mi
      ephemeral-storage: 1Gi

rabbitmq:
  name: rabbitmq
  image: rabbitmq
  tag: 4-management
  containerPort: 5672
  managementPort: 15672
  servicePort: 5672
  managementServicePort: 15672
  username: umiko
  password: changeme
  storageSize: 1Gi
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: "1"
      memory: 1Gi
      ephemeral-storage: 1Gi