namespace: umiko-production

appTag: "0.5.0"

ingress:
  domain: umiko.example.com

clusterIssuer:
  enabled: true
  email: "info@umiko.example.com"

pgadmin:
  email: admin@umiko.example.com
  password: changeme

postgres:
  password: changeme

rabbitmq:
  password: changeme

observability:
  enabled: true
  prometheus:
    storageSize: 50Gi
  tempo:
    storageSize: 20Gi
  loki:
    storageSize: 20Gi
  grafana:
    adminPassword: changeme