name: Build
permissions:
  contents: read
  pull-requests: write

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Restore dependencies
        run: dotnet restore source/MadWorldNL.Umiko.slnx

      - name: Pull Docker images
        run: |
          docker pull postgres:17.6 &
          docker pull rabbitmq:4.2 &
          wait

      - name: Build
        run: dotnet build source/MadWorldNL.Umiko.slnx --no-restore --configuration Release

      - name: Test
        run: dotnet test source/MadWorldNL.Umiko.slnx --no-build --configuration Release