name: Build & Test Application
permissions:
  contents: read
  pull-requests: write

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Install dev certificates
        run: |
          dotnet tool update -g linux-dev-certs
          dotnet linux-dev-certs install
          dotnet dev-certs https --clean
          dotnet dev-certs https --trust

      - name: Install Playwright browsers
        working-directory: source/MadWorldNL.Umiko.Controllers.EndToEndTests
        run: |
          dotnet tool install --global Microsoft.Playwright.CLI
          playwright install chromium

      - name: Restore dependencies
        run: dotnet restore source/MadWorldNL.Umiko.slnx

      - name: Build
        run: dotnet build source/MadWorldNL.Umiko.slnx --no-restore --configuration Release

      - name: Test
        run: dotnet test source/MadWorldNL.Umiko.slnx --no-build --configuration Release